---
title: "Data_cleaning"
author: "Sara Østergaard"
date: "2/10/2020"
output: 
  md_document:
    variant: markdown_github
---

```{r setup, include=FALSE}
require(knitr)
knitr::opts_chunk$set(echo = TRUE)
library(pacman)
pacman::p_load(dplyr, ggplot2, readr)
```

```{r load EyeLink data}
## Load sample data for both experiments
Foraging_Samples <- read_csv('Exported_EyeLink_data/Foraging_Samples.csv')
SocialEngagement_Samples <- read_csv('Exported_EyeLink_data/SocialEngagement_Samples.csv')

## Load fixations data for both experiments
Foraging_Fixations <- read_csv('Exported_EyeLink_data/Foraging_Fixations.csv')
SocialEngagement_Fixations <- read_csv('Exported_EyeLink_data/SocialEngagement_Fixations.csv')

## Load saccades data for both experiments
Foraging_Saccades <- read_csv('Exported_EyeLink_data/Foraging_Saccades.csv')
SocialEngagement_Saccades <- read_csv('Exported_EyeLink_data/SocialEngagement_Saccades.csv')
```

```{r add gender and task info}
## We have made a small function to make things easier for your.
## What does the function do?

Add_Info <- function(df){
  
  df$Task[grepl("_",df$RECORDING_SESSION_LABEL)]='Foraging'
  df$Task[!grepl("_",df$RECORDING_SESSION_LABEL)]='SocialEngagement'
  
  df$ParticipantGender[grepl("F",df$RECORDING_SESSION_LABEL)]='Female'
  df$ParticipantGender[grepl("M",df$RECORDING_SESSION_LABEL)]='Male'
  
  df$SearchOrder[grepl("_1",df$RECORDING_SESSION_LABEL)]=1
  df$SearchOrder[grepl("_2",df$RECORDING_SESSION_LABEL)]=2
  
  return(df)
}

## Run the function on the datasets
Foraging_Samples <- Add_Info(Foraging_Samples) 
Foraging_Fixations <- Add_Info(Foraging_Fixations) 
Foraging_Saccades <- Add_Info(Foraging_Saccades)
SocialEngagement_Samples <- Add_Info(SocialEngagement_Samples)
SocialEngagement_Fixations <- Add_Info(SocialEngagement_Fixations)
SocialEngagement_Saccades <- Add_Info(SocialEngagement_Saccades)
```

```{r bind the dataframes}
## Use rbind() to make collapse across experiments
Samples <- rbind(Foraging_Samples, SocialEngagement_Samples)
Fixations <- rbind(Foraging_Fixations, SocialEngagement_Fixations)
Saccades <- rbind(Foraging_Saccades, SocialEngagement_Saccades) 
```


```{r keep only needed variables}
Samples = Samples %>% 
  select(
    ParticipantID=RECORDING_SESSION_LABEL,
    Trial=TRIAL_INDEX,
    Time=TIMESTAMP,
    LeftGazeX=LEFT_GAZE_X,
    LeftGazeY=LEFT_GAZE_Y,
    RightGazeX=RIGHT_GAZE_X,
    RightGazeY=RIGHT_GAZE_Y,
    LeftPupilSize=LEFT_PUPIL_SIZE,
    RightPupilSize=RIGHT_PUPIL_SIZE,
    Task,
    ParticipantGender,
    SearchOrder
    ) 

Fixations = Fixations %>% 
  select(
    ParticipantID=RECORDING_SESSION_LABEL,
    Trial=TRIAL_INDEX,
    FixationNo=CURRENT_FIX_INDEX,
    StartTime=CURRENT_FIX_START,
    EndTime=CURRENT_FIX_END,
    Duration=CURRENT_FIX_DURATION,
    PositionX=CURRENT_FIX_X,
    PositionY=CURRENT_FIX_Y,
    PupilSize=CURRENT_FIX_PUPIL,
    EyeUsed=EYE_USED,
    Task,
    ParticipantGender,
    SearchOrder
    ) 

Saccades = Saccades %>%
  select(
    ParticipantID=RECORDING_SESSION_LABEL,
    Trial=TRIAL_INDEX,
    SaccadeNo=CURRENT_SAC_INDEX,
    StartTime=CURRENT_SAC_START_TIME,
    EndTime=CURRENT_SAC_END_TIME,
    Duration=CURRENT_SAC_DURATION,
    StartX=CURRENT_SAC_START_X,
    StartY=CURRENT_SAC_START_Y,
    EndX=CURRENT_SAC_END_X,
    EndY=CURRENT_SAC_END_Y,
    PeakVelocity=CURRENT_SAC_PEAK_VELOCITY,
    MeanVelocity=CURRENT_SAC_AVG_VELOCITY,
    Blink=CURRENT_SAC_CONTAINS_BLINK,
    Direction=CURRENT_SAC_DIRECTION,
    Amplitude=CURRENT_SAC_AMPLITUDE,
    EyeUsed=EYE_USED,
    Task,
    ParticipantGender,
    SearchOrder)


```

```{r remove NAs in left/right gaze}
#Changing the missing values from . to NA
Samples[Samples == "."] <- NA

Samples <- Samples %>% 
  mutate(
    #Making combined gaze rows for x and y (instead of different ones for left and right eye)
    GazeX = ifelse(is.na(RightGazeX), LeftGazeX,RightGazeX),
    GazeY = ifelse(is.na(RightGazeY), LeftGazeY,RightGazeY),
    #Making combined pupil size
    PupilSize = ifelse(is.na(RightPupilSize), LeftPupilSize, RightPupilSize)
  )

#Remove the left/right columns
Samples <- subset(Samples, select = -c(RightGazeX, RightGazeY, LeftGazeX, LeftGazeY, RightPupilSize, LeftPupilSize))

```


```{r fix problem with extra zeros}
## The problem is that Excel (which we have used to export the data to CSV) adds two extra zeros
## to each number, then transforms it into a character *facepalm*.
## So each variable below has to bee transformed to a numeric, then divided by 100 to remove
## the extra zeros

# Samples <- Samples %>% 
#   group_by(ParticipantID, Trial) %>% 
#   mutate(Time = (Time-Time[1])/100,
#          LeftGazeX = as.numeric(LeftGazeX)/100,
#          LeftGazeY = as.numeric(LeftGazeY)/100,
#          RightGazeX = as.numeric(RightGazeX)/100,
#          RightGazeY = as.numeric(RightGazeY)/100,
#          LeftPupilSize = as.numeric(LeftPupilSize)/100,
#          RightPupilSize = as.numeric(RightPupilSize)/100)

Samples <- Samples %>% 
  group_by(ParticipantID, Trial) %>% 
  mutate(Time = (Time-Time[1])/100,
         GazeX = as.numeric(GazeX)/100,
         GazeY = as.numeric(GazeY)/100,
         PupilSize = as.numeric(PupilSize)/100
         )

Fixations <- Fixations %>% 
  mutate(PositionX = as.numeric(PositionX)/100,
         PositionY = as.numeric(PositionY)/100,
         PupilSize = as.numeric(PupilSize)/100)

Saccades <- Saccades %>% 
  mutate(StartX = as.numeric(StartX)/100,
         StartY = as.numeric(StartY)/100,
         EndX = as.numeric(EndX)/100,
         EndY =as.numeric(EndY)/100,
         PeakVelocity = as.numeric(PeakVelocity)/100,
         ## this is just because the MeanVelocity columns has commas instead of points
         MeanVelocity = as.numeric(gsub(";", ".", MeanVelocity)))
```


## Merge with PsychoPy logfiles

```{r}
## For the Foraging task using the left_join() function
logfiles_Foraging <- read.csv('logfiles_Foraging/ForagingOrder.csv')
Samples <- left_join(Samples, logfiles_Foraging, by = c("Trial", "SearchOrder")) 
# Joining, by = c("Trial", "SearchOrder")

## For the Social Engagement task using the left_join() function
logfiles_SocialEngagement <- read.csv('logfiles_SocialEngagement/logfiles_SocialEngagement.csv')
Samples <- left_join(Samples, logfiles_SocialEngagement, by = c("ParticipantID", "Trial")) 
# Joining, by = c("ParticipantID", "Trial")
```


```{r save files}
write_csv(Samples, "Exported_EyeLink_data/Cleaned/Samples.csv")
write_csv(Fixations, "Exported_EyeLink_data/Cleaned/Fixations.csv")
write_csv(Saccades, "Exported_EyeLink_data/Cleaned/Saccades.csv")

```


## Import fixation number and saccade number from processed data to samples

```{r}

## WARNING: THIS MAY TAKE A WHILE!

for (t in seq(nrow(Fixations))){
  StartTime=Fixations$StartTime[t]
  EndTime=Fixations$EndTime[t]
  ID=Fixations$ParticipantID[t]
  Trial=Fixations$Trial[t]
  FixN=Fixations$FixationNo[t]
  Samples$FixationNo[Samples$Time >= StartTime  & Samples$Time <= EndTime & Samples$ParticipantID==ID & Samples$Trial==Trial]=FixN
}

for (t in seq(nrow(Saccades))){
  StartTime=Saccades$StartTime[t]
  EndTime=Saccades$EndTime[t]
  ID=Saccades$ParticipantID[t]
  Trial=Saccades$Trial[t]
  SacN=Saccades$SaccadeNo[t]
  Samples$SaccadeNo[Samples$Time >= StartTime  & Samples$Time <= EndTime & Samples$ParticipantID==ID & Samples$Trial==Trial]=SacN
}

write_csv(Samples, "Exported_EyeLink_data/Cleaned/Samples_merged_self.csv")
```

```{r}
#Load merged data
Samples_merged <- read_csv('Exported_EyeLink_data/Cleaned/Samples_merged_Fabio.csv')
```


# SANITY CHECKS

```{r}
## Check distribution of fixations
# Number of fixations
FixN <- Samples_merged %>% 
  group_by(ParticipantID, Trial, Task) %>% 
  dplyr::summarise(
    Count = max(FixationNo, na.rm=TRUE)
  )

ggplot(FixN, aes(Count, color = ParticipantID, fill = ParticipantID))+
  geom_density(alpha = .3)+
  facet_wrap(.~Task)+
  geom_rug(aes(x = Count, y = 0))

# Fixation duration
FixD <- Samples_merged[!is.na(Samples_merged$FixationNo),] %>% 
  #subset(!is.na(FixationNo)) %>% => another way of doing it
  group_by(Task, ParticipantID, Trial, FixationNo) %>% 
  dplyr::summarise(
    Duration = max(Time, na.rm = T)-min(Time, na.rm = T)
  )

ggplot(FixD, aes(Duration, color = ParticipantID, fill = ParticipantID))+
  geom_density(alpha = .3)+
  facet_wrap(.~Task)+
  geom_rug(aes(x = Duration, y = 0))

## Check distribution of saccades


## Remove all the data points that fall outside of the screen coordinates
## (1680, 1050), since these are artefacts


## Check distribution of pupil sizes for the Social Engagement task


```

```{r}
## Check for outliers in fixation durations using a boxplot


## Check for outliers in saccade velocity using a boxplot

```


# MAKE SOME PRELIMINARY VISUALIZATIONS TO EYEBALL THE DATA

```{r}
## Make a plot using geom_point and geom_line to visualize fixation duration
## in the two experiments


```


```{r}
## Make a plot using geom_point and geom_line to visualize saccade amplitude
## in the two experiments


```


```{r}
## Make a density plot visualizing pupil size by gender and by experiment


```


# SOME MORE ADVANCED VISUALIZATIONS


## Heatmaps

```{r}
## Make a heatmap for fixation density across the two experiments


```


```{r}
## Make a heatmap for fixation density for the "sheep.jpg" stimulus, divided by the
## two visual foraging tasks (Count vs. Search)


```


```{r}
## Make the same heatmap, this time plotting fixation duration, and compare with the previous

```


## Scanpaths

```{r}
## Using a for-loop, make a scanpath for each participant in the Foraging experiment. Use facets to plot the 10
## trials separately for each participant. Use these plots as diagnostic tools in order to answer the following
## questions:
## 
## 1) Do the data look reasonable and of good quality? Do we have any issues?
## 2) Can we differentiate between the two conditions (Count and Search) only by looking at the scanpaths?
## 3) Can we spot the trials in which the participants found the star?

f1_t1 <- subset(Samples_merged, ParticipantID == 'F1' & Trial == 1)

fixations_sample <- f1_t1[!is.na(Samples_merged$FixationNo),] %>% 
  group_by(Task, ParticipantID, Trial, FixationNo) %>% 
  dplyr::summarise(
    Duration = max(Time, na.rm = T)-min(Time, na.rm = T),
    meanX = mean(RightGazeX),
    meanY = mean(LeftGazeY)
  )


```


```{r}
## Do the same analysis for the Social Engagement task (eyeballing differences due to the two
## experimental conditions, i.e., Ostensiveness and Directionality)


```


## AOIs

```{r}
## Using the 'sheep.jpg' picture, draw an AOI around the black sheep in the foreground.
## Then make a count of how many fixations happen inside that AOI


```


```{r}
## Do the same thing for fixation duration


```

```{r}
## Find the star in the 'penguins.jpg' picture. Draw an AOI around it, then compute 
## Time to First Fixation to that AOI


```